name: Terraform Apply DB Fail over

on:
  push:
    branches:
      - venkat-cloudathon-terraform-workflow
    paths:
      - 'Postgresql_failover/**'

jobs:
  terraform-apply:
    name: Terraform Apply DB
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./cloudathon

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Google Cloud SDK
      - name: Setup GCP Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.ltc_hack_prj_1_service_account }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize Terraform with GCP provider
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.ltc_hack_prj_1_service_account }}

      # Format Terraform files recursively
      - name: Terraform Format
        run: terraform fmt -check -recursive
        continue-on-error: true

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.ltc_hack_prj_1_service_account }}
          
      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.ltc_hack_prj_1_service_account }}
      
      # # Terraform Destroy
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.ltc_hack_prj_1_service_account }}
      
